; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	zinggjm/GxEPD2
	olikraus/U8g2_for_Adafruit_GFX
	bblanchon/ArduinoJson
	geekfactory/GeekFactory GFButton Library@^1.0.1
	wallysalami/QRCodeGFX@^1.0.0
	miguelbalboa/MFRC522
	256dpi/MQTT
monitor_speed = 115200
